---
repositories:
- name: helloworld
  url: git+https://github.com/rahulwagh/helmchart@helloworld?ref=master&sparse=0

---
releases:
- name: userapi
  chart: ./webapi1-chart
  installed: true

- name: weatherapi
  chart: ./webapi2-chart
  installed: true

- name: getwayapi
  chart: ./getwayapi-chart
  installed: true
