FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /src

COPY ./GetwayApi GetwayApi/
RUN dotnet restore GetwayApi/GetwayApi.csproj

WORKDIR /src/GetwayApi
RUN dotnet publish -c Release -o /src/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /src/out .

EXPOSE 80
EXPOSE 443
ENTRYPOINT [ "dotnet", "GetwayApi.dll" ]