// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TimeOff.Models.LeaveApplication
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class LeaveApplicationReceived : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""LeaveApplicationReceived"",""namespace"":""TimeOff.Models.LeaveApplication"",""fields"":[{""name"":""LeaveGuid"",""type"":""string""},{""name"":""EmpEmail"",""type"":""string""},{""name"":""EmpDepartment"",""type"":""string""},{""name"":""LeaveDurationInHours"",""type"":""int""},{""name"":""LeaveStartDateTicks"",""type"":""long""}]}");
		private string _LeaveGuid;
		private string _EmpEmail;
		private string _EmpDepartment;
		private int _LeaveDurationInHours;
		private long _LeaveStartDateTicks;
		public virtual Schema Schema
		{
			get
			{
				return LeaveApplicationReceived._SCHEMA;
			}
		}
		public string LeaveGuid
		{
			get
			{
				return this._LeaveGuid;
			}
			set
			{
				this._LeaveGuid = value;
			}
		}
		public string EmpEmail
		{
			get
			{
				return this._EmpEmail;
			}
			set
			{
				this._EmpEmail = value;
			}
		}
		public string EmpDepartment
		{
			get
			{
				return this._EmpDepartment;
			}
			set
			{
				this._EmpDepartment = value;
			}
		}
		public int LeaveDurationInHours
		{
			get
			{
				return this._LeaveDurationInHours;
			}
			set
			{
				this._LeaveDurationInHours = value;
			}
		}
		public long LeaveStartDateTicks
		{
			get
			{
				return this._LeaveStartDateTicks;
			}
			set
			{
				this._LeaveStartDateTicks = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.LeaveGuid;
			case 1: return this.EmpEmail;
			case 2: return this.EmpDepartment;
			case 3: return this.LeaveDurationInHours;
			case 4: return this.LeaveStartDateTicks;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.LeaveGuid = (System.String)fieldValue; break;
			case 1: this.EmpEmail = (System.String)fieldValue; break;
			case 2: this.EmpDepartment = (System.String)fieldValue; break;
			case 3: this.LeaveDurationInHours = (System.Int32)fieldValue; break;
			case 4: this.LeaveStartDateTicks = (System.Int64)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
